name: 'OSS analysis'
description: 'Analyse the dependabot alerts'
author: 'libin'
inputs:
  path:  # id of input
    description: 'File path'
    required: true
    default: 'vuln-analysis.yaml'
outputs:
  ticketLists: # id of output
    description: 'List of alerts which need a ticket'
runs:
  using: 'node12'
  main: 'index.js'
