name: 'OSS analysis'
description: 'Analyse the dependabot alerts'
author: 'libin'
inputs:
  path:  # id of input
    description: 'File path'
    required: true
    default: 'vulnAnalysis.json'
  name:
    description: 'file name'
    required: false
    default: 'vulnAnalysis'
  token:
    description: 'jira authentication token'
    required: true
    default: ''
  jira_url:
    description: "jira host url"
    required: true
    default: ''
outputs:
  ticketLists: # id of output
    description: 'List of alerts which need a ticket'
runs:
  using: 'node12'
  main: 'index.js'
